services:
  app:
    build: .
    platform: linux/arm64
    image: trinket/app:latest
    ports:
      - 3000:3000
    container_name: trinket
    command: node app.js
    volumes:
      - .:/usr/local/node/trinket
      - /usr/local/node/trinket/node_modules
      - /usr/local/node/trinket/public/css
      - /usr/local/node/trinket/public/components
    environment:
      NODE_ENV: development
      GOOGLE_CLOUD_PROJECT: demo-trinket
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8080
      SESSION_PASSWORD: ${SESSION_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: http://localhost:3000/auth/google/callback
      NODE_CONFIG: >-
        {"app":{"url":{"hostname":"localhost","protocol":"http","port":3000},"plugins":{"session":{"cache":{"backend":"memory"}}},"auth":{"google":{"callbackURL":"http://localhost:3000/auth/google/callback"}}},"db":{"backend":"firestore","firestore":{"projectId":"demo-trinket"},"redis":{"enabled":false}}}
