app:
  usersubdomains: false
  start: false
  log:
    level: error
  trinketLibraryUser: testlibraryuser
db:
  mongo:
    host: localhost
    port: 27017
    database: test
  redis:
    enabled: false
